### ISSUE TITLE
Mod thumbnail documentation

### ISSUE THREAD

**Issue by improvshark** [stacklandsdev/modding-wiki#2]
I am having trouble uploading a steam workshop thumbnail. I was unable to find any documentation on how this is done in regards to Stacklands. Is this something that can be added to the publishing section?

**Comment by Sightwalker** [comment]
Ok. With some struggle I managed to do it: I created a 512x512 image file (PNG) and named it icon.png and put it in the source folder next to manifest.json. Then I built, commited and then updated the mod and now it has a thumbnail at the workshop!

**Comment by Cyber28** [comment]
@Sightwalker is right, i added it in the latest commit! https://modding.stacklands.co/en/latest/guides/publishing.html#adding-a-thumbnail

**Comment by improvshark** [comment]
Awesome Thank you.
